### ISSUE TITLE
Privacy Parameters

### ISSUE THREAD

**Issue by tz1998** [visitworld123/FedFed#4]
Hi,

thank you for your very interesting paper and code. I was taking a look at the privacy analysis in Appendix D , and I was curious as to what parameters were use. In particular, could you perhaps share which values were used for $`\delta`$ and $`\rho`$ when determining $` \epsilon`$  and/or $` \sigma`$  using the equation from Lemma D.2. 

As far as I understand $`\delta`$ and $`\rho`$  are fixed with the number of rounds $`R = 15`$ (for the VAE), and the privacy parameters $` \epsilon`$  and $` \sigma`$ are built around these constants.

Thank you in advance!

**Comment by visitworld123** [comment]
Thank you for your attention to our work. Because we only share protected features once which is not relevant to $R=15$ (VAE).
In FedFed, we mainly tune $\sigma$ to satisify differential privacy. Specifically, for $\sigma$ and $\epsilon$, we derive the privacy parameter $\epsilon$ from the noise parameter $\sigma$. (The detailed information can be seen in [former issue](https://github.com/visitworld123/FedFed/issues/2)). 

In Eq(9), we do not explicitly define a specific value of $\rho$, but instead implicitly control $\rho$ through a competition mechanism (This can be seen in the above section of Eq(8) `we propose an explicit competition mechanism in the
data space.`). So the $\rho$ value is related to the hyper-parameters of `VAE_re`,`VAE_ce` and `VAE_kl`. And we do not compute a certain $\delta$.

**Comment by visitworld123** [comment]
Further explanation: We only use DP protection when sharing performance-sensitive features, and it is shared only once. $R=15$ denotes the process of generating performance-sensitive features, which follows a standard FL process like FedAvg (as shown in Algorithm 1).

**Comment by MaxH1996** [comment]
Thank you very much, this clarifies my issue.

**Comment by tz1998** [comment]
Great, this clarifies my issue. 

Thank you for your thorough and quick response :)
